- menu_name: "Services"

- name: "Training"
  url: "/contact/"
  title: "Contact"

- name: "Education"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"

- name: "Consulting"
  url: "/atom.xml"
  title: "Subscribe to Atom Feed"

- name: "Contact"
  url: "/contact/"
  title: "Contact"
